baseURL = 'https://rodrigogmg.github.io/actividad22_1_RRH/'
languageCode = 'es'
title = 'Blog de Flores'
theme = "ananke"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "about"
        url = "/about/"
        weight = 0
    [[menu.main]]
        identifier = "posts"
        name = "posts"
        title = "posts"
        url = "/posts/"
        weight = 0
        [[menu.main]]
        identifier = "miembros"
        name = "miembros"
        title = "miembros"
        url = "/miembros/"
        weight = 0